include:
  - board: seeeduino_xiao_ble_zmk_usb
    shield: totem_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble_zmk_usb
    shield: totem_right
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble_zmk_usb
    shield: settings_reset
